# Generated by Django 5.2.3 on 2025-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="chat_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
